version: '3.7'
services:
  mysqldb:
    image: mysql:8.0
    ports:
      - '3306:3306'
    volumes:
      - ./artifacts/schema:/docker-entrypoint-initdb.d
      - ./data:/var/lib/mysql
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
      - MYSQL_DATABASE=app
      - MYSQL_USER=shade1471
      - MYSQL_PASSWORD=shade1471